extends Node2D

const rainbow_material = preload("res://Shaders/rainbow.tres")

var prev_r: int = 0

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	change_chair()
	if Global.rainbow_active && check_all_done():
		get_parent().material = rainbow_material

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass

func change_chair() -> void:
	var unblocked_chairs = []
	var i = 0
	#Get an array of all the blocked chairs
	for chair in Global.chairs:
		if chair == true:
			unblocked_chairs.append(i)
		i += 1
	var r = randi() % unblocked_chairs.size()
	r = unblocked_chairs[r]
	
	var chair = get_parent()
	
	if get_parent().get_child_count() > 1 && prev_r != r:
		get_node("../AnimationPlayer").play("change")
		$ChangeChairSFX.play()
	
	#Esto está feo... Pero ya me da igual.
	match r:
		0: chair.play("Chair")
		1: chair.play("Armchair")
		2: chair.play("Office")
		3: chair.play("Reclining")
		4: chair.play("Rocking")
		5: chair.play("Acapulco")
		6: chair.play("Hanging")
		7: chair.play("Chaise Longue")
		8: chair.play("Papasan")
		9: chair.play("Egg")
		10: chair.play("Gamer")
		11: chair.play("Ikea")
		12: chair.play("Japanese")
		13: chair.play("Toilet")
		14: chair.play("Folding")
		15: chair.play("Camping")
		16: chair.play("Street")
		17: chair.play("Deck")
		18: chair.play("Hammock")
		19: chair.play("Swing")
		20: chair.play("Wheel")
		21: chair.play("BabyWheel")
		22: chair.play("BabyFood")
		23: chair.play("BabyCar")
		24: chair.play("Child")
		25: chair.play("Car")
		26: chair.play("Bus")
		27: chair.play("Reserved")
		28: chair.play("Plane")
		29: chair.play("Pilot")
		30: chair.play("Copilot")
		31: chair.play("Rocket")
		32: chair.play("Ejectable")
		33: chair.play("Bar")
		34: chair.play("Cinema")
		35: chair.play("School")
		36: chair.play("Massage")
		37: chair.play("Barbershop")
		38: chair.play("Gym")
		39: chair.play("RollerCoaster")
		40: chair.play("Fair")
		41: chair.play("Stair")
		42: chair.play("Lifeguard")
		43: chair.play("Grandstand")
		44: chair.play("Director")
		45: chair.play("Wait")
		46: chair.play("Tennis")
		47: chair.play("Electric")
		48: chair.play("Trap")
		49: chair.play("Throne")
		50: chair.play("Elegant")
		51: chair.play("Steampunk")
		52: chair.play("Cyberpunk")
		53: chair.play("Funny")
		54: chair.play("Impressionist")
		55: chair.play("Cubist")
		56: chair.play("Surrealist")
		57: chair.play("Abstract")
		58: chair.play("Minimalist")
		59: chair.play("Pixel")
		60: chair.play("Gaudi")
		61: chair.play("Spheric")
		62: chair.play("Cubic")
		63: chair.play("Pyramid")
		64: chair.play("Stone")
		65: chair.play("Ice")
		66: chair.play("Fire")
		67: chair.play("Glass")
		68: chair.play("Diamond")
		69: chair.play("Paper")
		70: chair.play("Cardboard")
		71: chair.play("Slime")
		72: chair.play("Edible")
		73: chair.play("Sweet")
		74: chair.play("Natural")
		75: chair.play("Musical")
		76: chair.play("Block")
		77: chair.play("Dark")
		78: chair.play("Cloud")
		79: chair.play("Balloon")
		80: chair.play("Puzzle")
		81: chair.play("Naval")
		82: chair.play("Pirate")
		83: chair.play("Furry")
		84: chair.play("Alien")
		85: chair.play("Robot")
		86: chair.play("Magic")
		87: chair.play("Sleepy")
		88: chair.play("Zombie")
		89: chair.play("Vampire")
		90: chair.play("Frankenstein")
		91: chair.play("Mummy")
		92: chair.play("Ghost")
		93: chair.play("Christmas")
		94: chair.play("Fashion")
		95: chair.play("Angel")
		96: chair.play("Demon")
		97: chair.play("Bird")
		98: chair.play("RGB")
		99: chair.play("Casino")
		100: chair.play("Wide")
		101: chair.play("Tall")
		102: chair.play("Short")
		103: chair.play("Italic")
		104: chair.play("Big")
		105: chair.play("Mini")
		106: chair.play("Micro")
		107: chair.play("BadIdea")
		108: chair.play("Fakir")
		109: chair.play("Flamingo")
		110: chair.play("Biped")
		111: chair.play("Tripod")
		112: chair.play("FiveLegged")
		113: chair.play("Centipede")
		114: chair.play("Siamese")
		115: chair.play("Back")
		116: chair.play("Chary")
		117: chair.play("Sexy")
		118: chair.play("Chairette")
		119: chair.play("Rude")
		120: chair.play("Floating")
		121: chair.play("Distracted")
		122: chair.play("Cha")
		123: chair.play("Ir")
		124: chair.play("Invisible")
		125: chair.play("Anti")
		126: chair.play("Riahc")
		127: chair.play("Excalibur")
		128: chair.play("Ragebait")
		129: chair.play("Skeleton")
		130: chair.play("Doodle")
		131: chair.play("3D")
		132: chair.play("Realist")
		133: chair.play("Collage")
		134: chair.play("Icon")
		135: chair.play("LowRes")
		136: chair.play("Optic")
		137: chair.play("Atomic")
		138: chair.play("Constellation")
		139: chair.play("Infinite")
		140: chair.play("Conceptual")
		141: chair.play("Char")
		142: chair.play("Code")
		143: chair.play("Binary")
		144: chair.play("Textual")
		145: chair.play("Error")
		146: chair.play("Song")
		147: chair.play("MP3")
		148: chair.play("WordSearch")
		149: chair.play("Game")
		#FINALMENTE
		#ME DUELEN LOS DEDOS
	prev_r = r

func check_all_done() -> bool:
	var completed = true
	for chair in Global.chairs:
		if chair == false: completed = false
	return completed
